### ISSUE TITLE
Error - Internal error in Cloud Firestore (24.10.3). 

### ISSUE THREAD

**Issue by JahnabiMondal** [CMPUT301W24T25/Quemeful-QR#39]
This error occurred while running this app on 27th March, 2024, ( status of app - main merge #38 / and also same error on branch Jahnabi with 6 commits ahead).
Logcat error data below:

![error page1](https://github.com/CMPUT301W24T25/Quemeful-QR/assets/143971500/a22ded6b-ad5d-4e3a-a1b0-24fb9354404c)
![error page 2](https://github.com/CMPUT301W24T25/Quemeful-QR/assets/143971500/b808b83a-d50b-430e-aaca-36174ce691af)
![error page 3](https://github.com/CMPUT301W24T25/Quemeful-QR/assets/143971500/84dc3e0c-78f6-49ba-ab3e-9ee579a59d31)

**Comment by Endem14** [comment]
I tried to create an event and it works for me. I have old code and maybe thats why, as it tells that there is no issue with firebase and it might have something to do with the code you have.

**Comment by JahnabiMondal** [comment]
The code in the current main #38 it was me who merged it but only to update Javadocs and it ran fine only then I merged, also it works on everyone else's machines. Could you try checkout main and run it? no need to pull. 
Also, I haven't pushed the local commits I made and I'm getting this error regardless.
